# Generated by Django 4.0.4 on 2022-05-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='route',
            field=models.TextField(verbose_name='Route'),
        ),
    ]
