# Generated by Django 4.0.4 on 2022-05-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cargo_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.cargostatus', verbose_name='Status'),
            preserve_default=False,
        ),
    ]
