# Generated by Django 4.0.4 on 2022-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cargo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargostatus',
            name='code',
            field=models.CharField(default='', max_length=30, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
