# Generated by Django 4.0.4 on 2022-05-05 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cargostatus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.cargostatus', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CargoStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status_changes_new', to='core.cargostatus', verbose_name='New status')),
                ('old_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status_changes_old', to='core.cargostatus', verbose_name='Old status')),
            ],
            options={
                'verbose_name': 'Cargo Status Change',
                'verbose_name_plural': 'Cargo Status Changes',
            },
        ),
    ]
